/* Mock data for Field Shift. Every get*() function returns a Promise so it can later be swapped for
   fetch("/api/...") with no change in app.js. All values are DEMONSTRATION data. */
const cropData = [
 {id:'rice',name:'Rice',emoji:'🌾',season:'Summer',duration:'110–140 days',temp:'25–35°C',moisture:'High',soil:'Clay loam, holds water',nitrogen:'High',fertilizer:'Split nitrogen applications; avoid over-application near flowering.',water:3,waterLabel:'High',pests:'Stem borer, blast, brown planthopper',drought:'Low',legume:false,before:['Mung Bean','Wheat','Mustard','Lentil'],after:['Mung Bean','Wheat','Mustard','Lentil','Potato'],desc:"Bangladesh's staple cereal, grown in flooded or well-watered fields."},
 {id:'mung',name:'Mung Bean',emoji:'🫛',season:'Summer',duration:'60–75 days',temp:'25–35°C',moisture:'Moderate',soil:'Loam or sandy loam, well drained',nitrogen:'Low (fixes its own)',fertilizer:'Light phosphorus; little nitrogen needed.',water:1.5,waterLabel:'Moderate–Low',pests:'Yellow mosaic virus, pod borer',drought:'Moderate',legume:true,before:['Rice','Wheat','Jute'],after:['Rice','Wheat','Mustard'],desc:'A short-duration pulse that fits between main crops and adds nitrogen to the soil.'},
 {id:'wheat',name:'Wheat',emoji:'🌿',season:'Winter',duration:'105–120 days',temp:'15–25°C',moisture:'Moderate',soil:'Well-drained loam',nitrogen:'Moderate–High',fertilizer:'Nitrogen split between sowing and tillering.',water:2,waterLabel:'Moderate',pests:'Leaf rust, wheat blast, aphids',drought:'Moderate',legume:false,before:['Rice','Mung Bean','Jute'],after:['Rice','Mung Bean','Maize'],desc:'A cool-season cereal sown after the monsoon rice harvest.'},
 {id:'maize',name:'Maize',emoji:'🌽',season:'Winter',duration:'130–150 days',temp:'20–30°C',moisture:'Moderate',soil:'Fertile, well-drained loam',nitrogen:'High',fertilizer:'High demand; plan split nitrogen.',water:2.5,waterLabel:'Moderate–High',pests:'Fall armyworm, stalk rot',drought:'Low–Moderate',legume:false,before:['Mung Bean','Lentil','Rice'],after:['Mung Bean','Lentil','Wheat'],desc:'A high-yield cereal used for food and feed.'},
 {id:'lentil',name:'Lentil',emoji:'🫘',season:'Winter',duration:'100–115 days',temp:'15–25°C',moisture:'Low–Moderate',soil:'Loam, well drained',nitrogen:'Low (fixes its own)',fertilizer:'Minimal; small phosphorus dose.',water:1,waterLabel:'Low',pests:'Rust, stemphylium blight',drought:'High',legume:true,before:['Rice','Jute','Maize'],after:['Rice','Maize','Jute'],desc:'A drought-tolerant winter pulse.'},
 {id:'mustard',name:'Mustard',emoji:'🌼',season:'Winter',duration:'80–100 days',temp:'15–25°C',moisture:'Low–Moderate',soil:'Loam to clay loam',nitrogen:'Moderate',fertilizer:'Sulphur and boron often considered.',water:1.2,waterLabel:'Low–Moderate',pests:'Aphids, alternaria blight',drought:'Moderate–High',legume:false,before:['Rice','Mung Bean','Jute'],after:['Rice','Mung Bean','Jute'],desc:'A short winter oilseed that fits tight rotations.'},
 {id:'potato',name:'Potato',emoji:'🥔',season:'Winter',duration:'85–100 days',temp:'15–22°C',moisture:'Moderate',soil:'Loose, well-drained sandy loam',nitrogen:'High',fertilizer:'High nitrogen and potassium demand.',water:2.2,waterLabel:'Moderate',pests:'Late blight, tuber moth',drought:'Low',legume:false,before:['Rice','Jute','Mung Bean'],after:['Rice','Mustard','Mung Bean'],desc:'A cash crop grown in the cool dry months.'},
 {id:'jute',name:'Jute',emoji:'🌱',season:'Summer',duration:'110–130 days',temp:'24–37°C',moisture:'High',soil:'Alluvial loam',nitrogen:'Moderate',fertilizer:'Moderate nitrogen; organic matter helps.',water:2.5,waterLabel:'Moderate–High',pests:'Stem weevil, root rot',drought:'Low',legume:false,before:['Wheat','Mustard','Lentil','Potato'],after:['Wheat','Mustard','Lentil'],desc:'A fibre crop suited to warm, humid conditions.'},
 {id:'tomato',name:'Tomato',emoji:'🍅',season:'Winter',duration:'100–130 days',temp:'18–28°C',moisture:'Moderate',soil:'Fertile, well-drained loam',nitrogen:'Moderate–High',fertilizer:'Balanced feed; calcium considered.',water:2.2,waterLabel:'Moderate',pests:'Leaf curl virus, fruit borer',drought:'Low',legume:false,before:['Rice','Mung Bean'],after:['Rice','Mung Bean'],desc:'A high-value vegetable needing regular care.'},
 {id:'veg',name:'Vegetables',emoji:'🥬',season:'All Seasons',duration:'40–90 days',temp:'18–32°C',moisture:'Moderate',soil:'Rich loam with organic matter',nitrogen:'Moderate',fertilizer:'Compost plus targeted feed.',water:2,waterLabel:'Moderate',pests:'Aphids, caterpillars, wilts',drought:'Low',legume:false,before:['Rice','Mung Bean'],after:['Rice','Mung Bean'],desc:'Mixed seasonal vegetables for local markets.'}
];
const locations = {Rangpur:[25.75,89.25],Rajshahi:[24.37,88.6],Mymensingh:[24.75,90.4],Dhaka:[23.81,90.41],Khulna:[22.82,89.55]};
const defaultFarm = {location:'Rangpur, Bangladesh',size:'1.0',crop:'Rice',previous:'Rice',irrigation:'Limited',priority:'Water efficiency',soil:'Clay loam'};
const environmentalData = {rainfall:42,sunlight:6.8,soilMoisture:'Moderate',soilMoisturePct:55,temperature:29,vegetation:'Healthy',vegetationPct:78};
/* Candidate sequences the mock "engine" scores. A real backend would produce these. */
const rotationTemplates = [['Rice','Mung Bean','Rice'],['Rice','Wheat','Rice'],['Rice','Mustard','Rice'],['Rice','Lentil','Jute'],['Maize','Mung Bean','Wheat'],['Potato','Rice','Mustard']];
const whatIfScenarios = [{name:'Normal rainfall',water:0,note:'Baseline conditions.'},{name:'Lower rainfall',water:1,note:'Water-hungry crops face more stress.'},{name:'Higher temperature',water:0.5,note:'Heat can shorten planting windows for cool-season crops.'},{name:'Limited irrigation',water:1,note:'Needs reliable irrigation for later stages.'}];
const demoReferences = ['Placeholder: regional crop-rotation study A (fictional)','Placeholder: pulse nitrogen contribution review (fictional)','Placeholder: cereal water-use comparison (fictional)'];
/* Swap each body for fetch('/api/...').then(r=>r.json()) when the Python API exists. */
const delay=(v,ms=120)=>new Promise(r=>setTimeout(()=>r(v),ms));
const getCropData=()=>delay(cropData);
const getFarmData=()=>delay(JSON.parse(localStorage.getItem('fsFarm')||'null')||defaultFarm);
const saveFarmData=f=>{localStorage.setItem('fsFarm',JSON.stringify(f));return delay(f,0)};
const getEnvironmentalData=()=>delay(environmentalData);
const getRotationCandidates=()=>delay(rotationTemplates);
